### PR TITLE
Allow for ruby 3.

### PR DESCRIPTION
**Pull request by crondaemon**
Fix: #57.

### CODE REVIEW

**Comment by crondaemon** [comment]
It looks no issues with ruby 3, according to travis. I've updated the version constraint to `> 2.0`. While here I dropped the CI for older ruby versions.

**Comment by adfoster-r7** [comment]
@shadowbq It would be great to get this in if everything looks good to you :+1:

**Comment by adfoster-r7** [comment]
@crondaemon / @shadowbq Is there anything I can do to help get this landed? 🎉

**Comment by crondaemon** [comment]
I upvote for this, but I don't want to bypass @shadowbq and publish. I'd like to have an ok from him.

**Comment by anthraxx** [comment]
gentle ping

**Comment by crondaemon** [comment]
Gently bumping this MR again... @shadowbq anything blocking?

**Comment by crondaemon** [comment]
:+1: 
Are you going to release 0.13.1?

**Pull request merged**
