### PR TITLE
Drop support for older ruby versions.

### PR DESCRIPTION
**Pull request by crondaemon**
Fix: #47.

### CODE REVIEW

**Comment by picatz** [comment]
@crondaemon I guess someone had to do this eventually 😂 👏

**Comment by crondaemon** [comment]
@picatz I can merge this, since I have write access actually. I doesn't make really sense until the new gem will be release. I can't do that.

**Comment by picatz** [comment]
@crondaemon Gotch'a. Good to know. 👍 

@shadowbq Do you have any thoughts on this? Looks like a new gem version hasn't been released in two years.

**Comment by shadowbq** [comment]
Yes we should release a new gem.

**Comment by crondaemon** [comment]
Ok, then. I'd merge this and #52 before.

**Comment by shadowbq** [comment]
Do we want to go with this one only or setup a Milestone / and new release

**Comment by picatz** [comment]
@shadowbq A milestone seems _appropriate_ 😹 -- but maybe not totally necessary.

**Comment by crondaemon** [comment]
I'd go straight. The two of them are minor changes.

**Pull request merged**
